# SPDX-License-Identifier: GPL-2.0

obj-y += ebc_pmic.o ebc_pmic_mfd.o
obj-$(CONFIG_EBC_TPS65185_SENSOR) += tps65185.o
obj-$(CONFIG_EBC_SY7636A_PMIC) += sy7636a-regulator.o sy7636a-thermal.o
obj-$(CONFIG_EBC_SY7673A_PMIC) += sy7673a.o
